version: "3.9"
services: 
    web: 
        build: .
        ports: 
            - "5000:5000"
        networks:
            tuto-network:
                aliases: 
                    - uno


networks:
    tuto-network: 
        name: tuto-network
        driver: bridge